### ISSUE TITLE
Consider moving some fields out of `AnchorEvent `

### ISSUE THREAD

**Issue by en** [octopus-network/octopus-appchain-anchor#2]
https://github.com/octopus-network/octopus-appchain-anchor/blob/9db026e51be0fc871093f19532502a6c64c6fc46/appchain-anchor/src/message_decoder.rs#L40

In my understanding, the appchain does not need to know the following events:
`NearFungibleTokenUnlocked`
`FailedToUnlockNearFungibleToken`
`FailedToBurnWrappedAppchainToken`
`WrappedAppchainTokenMinted`
`FailedToMintWrappedAppchainToken`

Some of them are initiated by appchain, and some of them should be notified to users.
None of them need to be sent to the appchain.
If these fields exist in `AnchorEvent`, parsing on the appchain side becomes complicated.
The frontend may not be able to easily get these errors and inform users.

**Comment by riversyang** [comment]
As discussed with team, current interfaces related to `AnchorEvent` will remain unchanged. The anchor contract will add a new view function, which is only used to query the relevant events for appchain.

**Comment by en** [comment]
fixed by d7eb8f03f1c044713a4b5250dfbe084565d53475
